export const TestStopPoints: any = 
[ 
    {
        $type: "Tfl.Api.Presentation.Entities.Prediction, Tfl.Api.Presentation.Entities",
        id: "-985715108",
        operationType: 1,
        vehicleId: "054",
        naptanId: "940GZZLUTWH",
        stationName: "Tower Hill Underground Station",       
        lineName: "District",
        platformName: "Eastbound - Platform 3",
        direction: "outbound",       
        destinationNaptanId: "940GZZLUBKG",
        destinationName: "Barking Underground Station",
        timestamp: "2021-04-06T06:49:57.7123404Z",
        timeToStation: 561,
        currentLocation: "Approaching Embankment",
        towards: "Barking",
        expectedArrival: "2021-04-06T06:59:18Z",
        timeToLive: "2021-04-06T06:59:18Z",
        modeName: "tube"
    },
    {
        $type: "Tfl.Api.Presentation.Entities.Prediction, Tfl.Api.Presentation.Entities",
        id: "-985715109",
        operationType: 1,
        vehicleId: "054",
        naptanId: "940GZZLUTWH",
        stationName: "Tower Hill Underground Station",       
        lineName: "District",
        platformName: "Westbound - Platform 3",
        direction: "outbound",       
        destinationNaptanId: "940GZZLUBKG",
        destinationName: "Barking Underground Station",
        timestamp: "2021-04-06T06:49:57.7123404Z",
        timeToStation: 561,
        currentLocation: "Approaching Embankment",
        towards: "Barking",
        expectedArrival: "2021-04-06T06:59:18Z",
        timeToLive: "2021-04-06T06:59:18Z",
        modeName: "tube"
    },
    {
        $type: "Tfl.Api.Presentation.Entities.Prediction, Tfl.Api.Presentation.Entities",
        id: "-985715110",
        operationType: 1,
        vehicleId: "054",
        naptanId: "940GZZLUTWH",
        stationName: "Tower Hill Underground Station",       
        lineName: "District",
        platformName: "Eastbound - Platform 3",
        direction: "outbound",       
        destinationNaptanId: "940GZZLUBKG",
        destinationName: "Barking Underground Station",
        timestamp: "2021-04-06T06:49:57.7123404Z",
        timeToStation: 561,
        currentLocation: "Approaching Embankment",
        towards: "Barking",
        expectedArrival: "2021-04-06T06:59:18Z",
        timeToLive: "2021-04-06T06:59:18Z",
        modeName: "tube"
    },
    {
        $type: "Tfl.Api.Presentation.Entities.Prediction, Tfl.Api.Presentation.Entities",
        id: "-985715111",
        operationType: 1,
        vehicleId: "054",
        naptanId: "940GZZLUTWH",
        stationName: "Tower Hill Underground Station",       
        lineName: "District",
        platformName: "Westbound - Platform 3",
        direction: "outbound",       
        destinationNaptanId: "940GZZLUBKG",
        destinationName: "Barking Underground Station",
        timestamp: "2021-04-06T06:49:57.7123404Z",
        timeToStation: 561,
        currentLocation: "Approaching Embankment",
        towards: "Barking",
        expectedArrival: "2021-04-06T06:59:18Z",
        timeToLive: "2021-04-06T06:59:18Z",
        modeName: "tube"
    },
    {
        $type: "Tfl.Api.Presentation.Entities.Prediction, Tfl.Api.Presentation.Entities",
        id: "-985715108",
        operationType: 1,
        vehicleId: "054",
        naptanId: "940GZZLUTWH",
        stationName: "Tower Hill Underground Station",       
        lineName: "District",
        platformName: "Eastbound - Platform 3",
        direction: "outbound",       
        destinationNaptanId: "940GZZLUBKG",
        destinationName: "Barking Underground Station",
        timestamp: "2021-04-06T06:49:57.7123404Z",
        timeToStation: 561,
        currentLocation: "Approaching Embankment",
        towards: "Barking",
        expectedArrival: "2021-04-06T06:59:18Z",
        timeToLive: "2021-04-06T06:59:18Z",
        modeName: "tube"
    },
    {
        $type: "Tfl.Api.Presentation.Entities.Prediction, Tfl.Api.Presentation.Entities",
        id: "-985715109",
        operationType: 1,
        vehicleId: "054",
        naptanId: "940GZZLUTWH",
        stationName: "Tower Hill Underground Station",       
        lineName: "District",
        platformName: "Westbound - Platform 3",
        direction: "outbound",       
        destinationNaptanId: "940GZZLUBKG",
        destinationName: "Barking Underground Station",
        timestamp: "2021-04-06T06:49:57.7123404Z",
        timeToStation: 561,
        currentLocation: "Approaching Embankment",
        towards: "Barking",
        expectedArrival: "2021-04-06T06:59:18Z",
        timeToLive: "2021-04-06T06:59:18Z",
        modeName: "tube"
    },
    {
        $type: "Tfl.Api.Presentation.Entities.Prediction, Tfl.Api.Presentation.Entities",
        id: "-985715110",
        operationType: 1,
        vehicleId: "054",
        naptanId: "940GZZLUTWH",
        stationName: "Tower Hill Underground Station",       
        lineName: "District",
        platformName: "Eastbound - Platform 3",
        direction: "outbound",       
        destinationNaptanId: "940GZZLUBKG",
        destinationName: "Barking Underground Station",
        timestamp: "2021-04-06T06:49:57.7123404Z",
        timeToStation: 561,
        currentLocation: "Approaching Embankment",
        towards: "Barking",
        expectedArrival: "2021-04-06T06:59:18Z",
        timeToLive: "2021-04-06T06:59:18Z",
        modeName: "tube"
    },
    {
        $type: "Tfl.Api.Presentation.Entities.Prediction, Tfl.Api.Presentation.Entities",
        id: "-985715111",
        operationType: 1,
        vehicleId: "054",
        naptanId: "940GZZLUTWH",
        stationName: "Tower Hill Underground Station",       
        lineName: "District",
        platformName: "Westbound - Platform 3",
        direction: "outbound",       
        destinationNaptanId: "940GZZLUBKG",
        destinationName: "Barking Underground Station",
        timestamp: "2021-04-06T06:49:57.7123404Z",
        timeToStation: 561,
        currentLocation: "Approaching Embankment",
        towards: "Barking",
        expectedArrival: "2021-04-06T06:59:18Z",
        timeToLive: "2021-04-06T06:59:18Z",
        modeName: "tube"
    }            
];